// <auto-generated />
namespace BeginApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DropSomeClumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropSomeClumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201405280751463_DropSomeClumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
