// <auto-generated />
namespace BeginApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class isAdmited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isAdmited));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241642477_isAdmited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
